# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160W8c4_fcgNGLqzWKQB_cX7_FbgmYhXD
"""

# app.py

import streamlit as st

st.set_page_config(page_title="Event Study App", layout="wide")

st.title("📊 Event Study - Cumulative Abnormal Returns (CAR) Viewer")
st.markdown("""
Welcome to the Event Study App!

Use the sidebar to navigate between pages:
- **Home**: About the project.
- **Dashboard**: Select stock and see CAR analysis.
- **Event Browser**: View event data.
- **About**: Project info and data sources.
""")