# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DV0mIHC1To4-qFDsj7tBQGZMb5rvUsy0
"""

# utils.py - Using local dummy CSV in root folder

import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt


def load_stock_data(ticker, start_date, end_date, file_path='dummy_stock_prices_2024_to_2025.csv'):
    """
    Load stock price data for a given ticker and date range from local CSV.
    """
    df = pd.read_csv(file_path, parse_dates=['date'])
    df = df[df['ticker'] == ticker].copy()
    df = df.set_index('date')
    df = df.loc[start_date:end_date]

    if df.empty:
        raise ValueError(f"No data for {ticker} between {start_date} and {end_date}")

    return df[['price']]


def load_market_data(start_date, end_date, file_path='dummy_stock_prices_2024_to_2025.csv'):
    """
    Simulate market index using average of all stock prices.
    """
    df = pd.read_csv(file_path, parse_dates=['date'])
    df = df[(df['date'] >= start_date) & (df['date'] <= end_date)]
    market = df.groupby('date')['price'].mean().reset_index()
    market = market.set_index('date')
    market.rename(columns={'price': 'market_price'}, inplace=True)
    return market


def calculate_market_model_car(stock_prices, market_prices, event_date, window=60):
    merged = pd.merge(stock_prices, market_prices, left_index=True, right_index=True, how='inner')
    merged['stock_return'] = merged['price'].pct_change()
    merged['market_return'] = merged['market_price'].pct_change()
    merged = merged.dropna()

    X = sm.add_constant(merged['market_return'])
    y = merged['stock_return']
    model = sm.OLS(y, X).fit()

    merged['expected_return'] = model.predict(X)
    merged['abnormal_return'] = merged['stock_return'] - merged['expected_return']

    nearest_idx = merged.index.get_indexer([event_date], method='nearest')[0]
    start_idx = max(nearest_idx - window // 2, 0)
    end_idx = min(nearest_idx + window // 2, len(merged))
    event_window = merged.iloc[start_idx:end_idx].copy()

    event_window['days_from_event'] = range(-len(event_window) // 2, len(event_window) // 2)
    event_window.set_index('days_from_event', inplace=True)
    event_window['CAR'] = event_window['abnormal_return'].cumsum()

    return event_window[['stock_return', 'expected_return', 'abnormal_return', 'CAR']]


def plot_car_graph(results):
    fig, ax = plt.subplots(figsize=(8, 5))
    jump = results['abnormal_return'].cumsum().iloc[-1] * 100 if 0 in results.index else 0

    car = [0 if day < 0 else jump for day in results.index]
    ax.plot(results.index, car, color='blue', linewidth=2)
    ax.axhline(0, color='black')
    ax.axvline(0, color='black', linestyle='--')

    ax.set_title('Mean CAR Graph', fontsize=16, color='red')
    ax.set_ylabel('% CAR')
    ax.set_xlabel('Days Relative to Event')
    ax.set_ylim(min(-5, jump - 1), max(5, jump + 1))
    return fig


def plot_ci_graph(results):
    abnormal_returns = results['abnormal_return']
    n = len(abnormal_returns)
    mean = abnormal_returns.cumsum()
    se = abnormal_returns.std() / (n ** 0.5)

    ci_upper = mean + 1.96 * se
    ci_lower = mean - 1.96 * se
    x_range = range(-len(mean) // 2, len(mean) // 2)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(x_range, mean, color='purple', label='Mean')
    ax.plot(x_range, ci_upper, linestyle='dotted', color='purple', label='Mean + 1.96SE')
    ax.plot(x_range, ci_lower, linestyle='dotted', color='purple', label='Mean - 1.96SE')

    ax.axhline(0, color='black', linestyle='--')
    ax.axvline(0, color='black', linestyle='--')
    ax.set_title('Cumulative Average Abnormal Return and 95% Confidence Limits', fontsize=16, color='red')
    ax.set_xlabel('Day Relative to Event')
    ax.set_ylabel('Return')
    ax.legend()
    return fig
