# -*- coding: utf-8 -*-
"""1_Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14g_lZ7oPDHi2Y5fuGUZtJGsHjoy-EP7m
"""

import streamlit as st

# Set Page Config
st.set_page_config(
    page_title="Event Study App",
    page_icon="📈",
    layout="centered"
)

# Custom CSS for background and text styling
st.markdown("""
    <style>
    .css-18e3th9 {
        padding-top: 2rem;
    }
    .stButton>button {
        width: 100%;
        padding: 1rem 2rem;
        font-size: 1.5rem;
        font-weight: bold;
        margin-bottom: 1rem;
    }
    h1 {
        text-align: center;
        color: white;
        font-size: 4rem;
        font-weight: 900;
        text-shadow:
            -2px -2px 0 #000,
            2px -2px 0 #000,
            -2px 2px 0 #000,
            2px 2px 0 #000;
    }
    h3 {
        text-align: center;
        color: white;
        font-size: 2rem;
        font-weight: 700;
        text-shadow:
            -2px -2px 0 #000,
            2px -2px 0 #000,
            -2px 2px 0 #000,
            2px 2px 0 #000;
    }
    .stApp {
        background-image: url('https://plus.unsplash.com/premium_photo-1681487769650-a0c3fbaed85a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmluYW5jaWFsJTIwbWFya2V0fGVufDB8fDB8fHww');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }
    </style>
""", unsafe_allow_html=True)

# Title and subtitle
st.markdown("<h1>📈 Welcome to Event Study Dashboard</h1>", unsafe_allow_html=True)
st.markdown("<h3>Analyze the Impact of Real-World Events on Stock Performance</h3>", unsafe_allow_html=True)

st.markdown("###")

# Buttons to navigate to other pages
if st.button('🚀 Go to Event Study Dashboard'):
    st.switch_page("pages/2_event_study_dashboard.py")

if st.button('📰 Go to Event Browser'):
    st.switch_page("pages/1_event_browser.py")