# -*- coding: utf-8 -*-
"""pages/1_event_browser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MdOKxLPSG4zacAq2qJA05cpoo5667VV
"""

import streamlit as st
import pandas as pd
from event_scraper import get_live_events

# Streamlit page setup
st.set_page_config(page_title="Event Browser", page_icon="📰", layout="wide")
st.title("📰 Live Event Browser")

# Caching logic with refresh button
@st.cache_data(ttl=3600, show_spinner=False)
def load_event_data():
    return get_live_events()

# UI for refresh
if st.button("🔄 Get Latest News"):
    st.cache_data.clear()
    st.rerun()

# Load and show data
event_data = load_event_data()

# Optional filters
industries = sorted(event_data["industry"].dropna().unique())
selected_industry = st.selectbox("Filter by Industry", ["All"] + industries)

if selected_industry != "All":
    event_data = event_data[event_data["industry"] == selected_industry]

# Show table
st.markdown(f"### Showing {len(event_data)} Recent Events")
st.dataframe(
    event_data[["ticker", "event_date", "news_type", "sentiment", "headline", "link"]],
    use_container_width=True,
    hide_index=True
)