# -*- coding: utf-8 -*-
"""4_About.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfbUetXZe9DBjYoaKrbocRTLM1sT-pVp
"""

# pages/4_About.py

import streamlit as st

st.title("ℹ️ About This App")

st.markdown("""
This app analyzes the impact of tariff-related news on stock prices using Event Study Methodology.

**Features:**
- CAR Calculation (Market Adjusted Model for now)
- Confidence Interval Visualization
- Multi-Industry Stock Selection

**Built using**:
- Streamlit
- Yahoo Finance data
- Python, pandas, statsmodels, matplotlib

**Developer**: Glenn Castellino, Sidhant Sidhant, Yash Kothari
""")